# Generated by Django 3.2.12 on 2022-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=15, null=True)),
                ('plate_number', models.CharField(max_length=15, null=True)),
                ('date', models.DateField(max_length=27, null=True)),
                ('time_in', models.CharField(max_length=10, null=True)),
                ('time_out', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
